name: evac_tracker
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.1.4+15
environment:
  sdk: '>=3.8.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  smart_search_dropdown: ^0.0.4
  dropdown_search: ^6.0.0
  auto_size_text: 3.0.0
  device_info_plus: ^10.1.2
  permission_handler: ^12.0.1
  flutter_cached_pdfview: ^0.4.2
  badges: ^3.1.2
  cached_network_image: ^3.4.0
  collection: ^1.19.1
  dropdown_button2: 2.3.9
  easy_debounce: ^2.0.3
  equatable: ^2.0.7
  file_picker: ^8.0.7
  firebase_core: ^4.0.0
  #firebase_core_platform_interface: 5.0.0
  #firebase_core_web: 2.17.0
  #firebase_performance: 0.9.4+5
  #firebase_performance_platform_interface: 0.1.4+33
  #firebase_performance_web: 0.1.6+5
  flutter_animate: ^4.5.2
  firebase_messaging: ^16.0.0
  googleapis_auth: ^2.0.0
  rxdart: ^0.28.0
  get:
  flutter_local_notifications: ^19.4.0
  # flutter_barcode_scanner: ^2.0.0
  #flutter_cache_manager: 3.3.1
  flutter_keyboard_visibility: ^6.0.0
  http: ^1.2.2
  flutter_native_splash: ^2.4.6
  #flutter_plugin_android_lifecycle: 2.0.20
  flutter_slidable: ^4.0.0
  flutter_spinkit: ^5.2.1
  font_awesome_flutter: ^10.8.0
  from_css_color: 2.0.0
  go_router: ^16.0.0
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.12.3
  image_picker: ^1.1.2
  
  intl: ^0.20.2
  json_path: ^0.7.6
  mime_type: ^1.0.1
  page_transition: ^2.2.1

  photo_view: ^0.15.0

  provider: ^6.1.5
  google_mlkit_barcode_scanning: ^0.14.1
  shared_preferences: ^2.5.3
 
  slide_to_act: ^2.0.0
  just_audio: ^0.9.39
  audio_service: ^0.18.15
  audio_session: ^0.1.21
  fluttertoast: ^8.2.8
  #sqflite: 2.2.6
  sticky_headers: 0.3.0+2
  stop_watch_timer: ^3.1.1
  timeago: ^3.7.1
  torch_light:
  #universal_io: 2.2.2
  url_launcher: ^6.3.2
  #url_launcher_android: 6.3.0
  #url_launcher_ios: 6.2.5
  #url_launcher_platform_interface: 2.3.2
  video_player: ^2.10.0
  #video_player_android: 2.4.16
  #video_player_avfoundation: 2.6.1
  #video_player_platform_interface: 6.2.2
  #video_player_web: 2.3.1
  xml: 6.5.0
  package_info_plus: ^8.0.2
  widget_zoom: ^0.0.4
  

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  upgrader: ^11.4.0
  mobile_scanner: ^7.0.1
  location: ^8.0.1
  flutter_polyline_points: ^3.0.1
  flutter_dotenv: ^6.0.0

dependency_overrides:
  http: 1.4.0
  uuid: ^4.0.0
  win32: 5.5.1
  fluttertoast: 8.2.12

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  image: ^4.5.4
  #lints: 4.0.0
  dependency_validator: ^5.0.2

  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: 'launcher_icon'
  ios: true
  web:
    generate: false
  image_path: 'assets/images/adaptive_foreground_icon_new.png'
  adaptive_icon_background: '#ffffff'
  adaptive_icon_foreground: 'assets/images/adaptive_foreground_icon_new.png'

flutter_native_splash:
  image: assets/images/splash.gif
  color: "#ffffff"  # Set the background color
  android: true     # Enable Android splash screen
  ios: true         # Enable iOS splash screen
  image_width: 180  # Specify the width (in dp for Android, in points for iOS)
  image_height: 180  # Specify the height (optional)

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/credentials/
    - assets/lottie_animations/
    - assets/rive_animations/
    - assets/pdfs/
    - assets/u5ayxxt5clg5/

  
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

